version: '2'
services:
  z-nomp:
    image: z-nomp
    ports:
      - "8080:8080"
      - "3032:3032"
  btg:
    image: valar999/btg
    ports:
      - "18338:18338"
    volumes:
      - btg:/root/.bitcoingold
  redis:
    image: redis
    volumes:
      - btg_redis:/data
volumes:
  btg:
  btg_redis:
